### ISSUE TITLE
Совсем не понятны назначения команд обмена данными

### ISSUE THREAD

**Issue by alex-eri** [pikhovkin/omnicomm#1]
Cmd94, Cmd86 и прочее не понятны. может для них добавить синонимы?

**Comment by pikhovkin** [comment]
Почему непонятны? Например?

**Comment by alex-eri** [comment]
я всё ещё не нашел документацию к протоколу. И что именно делает команда под номером можно догадаться только по контексту.

Если поделитесь документацией, то напишу хай-левел класс

**Comment by pikhovkin** [comment]
отправил доку

**Comment by webstels** [comment]
> отправил доку

Добрый день, буду благодарен если поделитесь докой, или подскажите что надо отвечать в ответ на Cmd80?

**Comment by pikhovkin** [comment]
@webstels, в ответ на 0x80, сервер может ответить командой 0x81, но это не обязательная команда, скорее  ответом будет запрос данных командой 0x85 как в этом [тесте](https://github.com/pikhovkin/omnicomm/blob/main/omnicomm/tests/test_server.py#L27)
