### ISSUE TITLE
Длинные ответы

### ISSUE THREAD

**Issue by alex-eri** [pikhovkin/omnicomm#2]
```
File "c:\Projects\omnicomm\venv\Lib\site-packages\omnicomm\protocol.py", line 101, in unpack_crc
    return struct.unpack_from('>H', data, offset=offset)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack_from requires a buffer of at least 1354 bytes for unpacking 2 bytes at offset 1352 (actual buffer size is 1227)
```

Возможно стоит вернуть `None, remain` , когда не достаточно буфера пришло в ответе?

**Comment by alex-eri** [comment]
Также, возможно, стоит пропускать сообщения в команде 86, которые не может обработать парсер.

**Comment by pikhovkin** [comment]
Добавил в новой версии возврат ошибки `UnpackingCRCError`. Что делать при этой ошибке пусть решает разработчик сервера. Например, при перехвате этой ошибки можно вернуться к чтению сокета, чтобы добавить в буфер недостающие данные.

**Comment by alex-eri** [comment]
UnpackingCRCError это другой тип ошибки. Если сообщение с плохой контрольной суммой - его надо однозначно отбросить. Тут нужна именно ошибка о недостатке данных в буфере.

**Comment by alex-eri** [comment]
В буфере может быть сразу несколько ответов или не быть ни одного. Например при подключении регистратора я ему сразу пуляю серию команд. Он шлет мне ответы и их можно прочитать пачкой. Если ответы возвращать списком, то удобно обрабатывать случаи и когда команда одна, и когда их несколько, и когда их нет.

            cmds, remain = ServerProtocol.unpack(data)
            for cmd in cmds: .....

**Comment by pikhovkin** [comment]
> В буфере может быть сразу несколько ответов или не быть ни одного. Например при подключении регистратора я ему сразу пуляю серию команд. Он шлет мне ответы и их можно прочитать пачкой. Если ответы возвращать списком, то удобно обрабатывать случаи и когда команда одна, и когда их несколько, и когда их нет.

Как раз думал об этом. Залил реализацию
