### ISSUE TITLE
Отправка пустого контейнера

### ISSUE THREAD

**Issue by alex-eri** [pikhovkin/omnicomm#3]
При отправке команды 0x86 с значением `{'rec_id': 123}` (без сообщений) получаю на сервере пустую команду `{}`

Следует убрать строки

https://github.com/pikhovkin/omnicomm/blob/42b287bbbab64649b618f27ac9dbdc4fbf153db0/omnicomm/commands.py#L122-L123

**Comment by pikhovkin** [comment]
У команды 0x86 не поля rec_id, поэтому оно просто игнорируется и запаковывается с пустым содержанием.
Команда 0x86 с пустым содержанием сообщает серверу о том, что регистратор закончил передачу архива.

**Comment by alex-eri** [comment]
как это нет? чуть выше определение:

        return dict(rec_id=value[0], omnicomm_time=value[1], priority=value[2], unix_time=cls.to_unix_time(value[1]))

даже если предусмотреть то что в конце должен отправляться пустая команда, то все равно на обратном конце я должен получить то что отправляю без особых искажений.

Пустую команду можно формировать посылкой без `rec_id`. А сейчас она формируется пустым `msg`.

**Comment by pikhovkin** [comment]
> как это нет? чуть выше определение:
> 
> ```
>     return dict(rec_id=value[0], omnicomm_time=value[1], priority=value[2], unix_time=cls.to_unix_time(value[1]))
> ```

да, не туда смотрел, все верно

> даже если предусмотреть то что в конце должен отправляться пустая команда, то все равно на обратном конце я должен получить то что отправляю без особых искажений.
> 
> Пустую команду можно формировать посылкой без `rec_id`. А сейчас она формируется пустым `msg`.

значение `rec_id` при пустом `msgs` не имеет смысла, т.к. номер `rec_id` относится к первому сообщению в `msgs`

**Comment by alex-eri** [comment]
теперь понятно, было несоответствие проверок между приёмом и передачей.

П.С.

https://github.com/pikhovkin/omnicomm/blob/3f503f3925d5bfd0b504230aa7ee182c96053dc9/omnicomm/commands.py#L111

тут квадратные скобки лишние в обоих случаях

**Comment by pikhovkin** [comment]
> теперь понятно, было несоответствие проверок между приёмом и передачей. Может заодно добавить проверку на rec_id и время?

время тоже не имеет смысла без первого элемента в `msgs`

> П.С.
> 
> https://github.com/pikhovkin/omnicomm/blob/3f503f3925d5bfd0b504230aa7ee182c96053dc9/omnicomm/commands.py#L111
> 
> тут квадратные скобки лишние в обоих случаях

да, можно поправить
