### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by binakot** [pikhovkin/omnicomm#6]
Не нашел контактные данные, поэтому напишу сюда ;)

Сергей, Приветствую! Меня зовут Иван, недавно наткнулся на ваш репозиторий с ОМНИКОММ протоколом https://github.com/pikhovkin/omnicomm. Спасибо за вклад в Open Source. Пока искал Ваши контакты увидел у Вас репозиторий https://github.com/pikhovkin/postgresql-postgis-timescaledb, в котором Вы указали, что сделали его на основе моего https://github.com/binakot/PostgreSQL-PostGIS-TimescaleDB. Так что можно сказать, мы заочно уже знакомы ;) К чему я это все, у Вас не сохранилось документации на протоколы OMNICOMM? Я был бы очень признателен, если бы Вы поделились ими со мной ;)

**Comment by pikhovkin** [comment]
@binakot, вам тоже благодарность за вклад в Open Source!
Док отправлен.

**Comment by binakot** [comment]
> @binakot, вам тоже благодарность за вклад в Open Source! Док отправлен.

Благодарю!
