### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by Ermak1984** [pikhovkin/omnicomm#9]
Сергей, приветствую. Можно Вас попросить поделиться документацией по протоколу обмена Омникомм (Терминал <----> Сервер), если не сложно. itservis.nv@gmail.com

**Comment by pikhovkin** [comment]
отправлен

**Comment by webstels** [comment]
@pikhovkin Добрый день, если не сложно, можете тоже пожалуйста поделиться документацией по протоколу обмена, webstels@yandex.ru

**Comment by pikhovkin** [comment]
отправлено
